export interface CarItem {
  id: string;
  title: string;
  category: string;
  transmission: string;
  seats: number;
  fuel_type: string;
  range_or_mpg: string;
  price_per_day: number;
  image: string;
  description: string;
}

export const carData: CarItem[] = [
  {
    id: "CAR-001",
    title: "Tesla Model Y Long Range",
    category: "Electric Cruiser",
    transmission: "Automatic",
    seats: 5,
    fuel_type: "Electric",
    range_or_mpg: "330 miles range",
    price_per_day: 85,
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=600&q=80",
    description: "An ultra-smooth electric crossover engineered for silent highway cruising, tech enthusiasts, and eco-conscious road trips. Features Autopilot navigation, expansive panoramic glass roof, instant torque, and seamless access to superchargers for zero-emission travel.",
  },
  {
    id: "CAR-002",
    title: "Porsche 911 Carrera Cabriolet",
    category: "Luxury Sports",
    transmission: "Automatic (PDK)",
    seats: 2,
    fuel_type: "Premium Gasoline",
    range_or_mpg: "24 MPG",
    price_per_day: 250,
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=600&q=80",
    description: "A high-octane luxury convertible designed for adrenaline lovers and weekend thrill seekers. Drop the top to feel the ocean breeze, enjoy razor-sharp cornering along coastal highways, and savor the iconic roar of a twin-turbo flat-six engine.",
  },
  {
    id: "CAR-003",
    title: "Ford Bronco Wildtrak 4x4",
    category: "Off-Road Adventure SUV",
    transmission: "Automatic",
    seats: 5,
    fuel_type: "Gasoline",
    range_or_mpg: "18 MPG",
    price_per_day: 110,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80",
    description: "A rugged, trail-ready 4x4 built for off-road explorers, mountain campers, and wild expeditions. Outfitted with heavy-duty mud tires, removable doors and roof panels, high ground clearance, and G.O.A.T. terrain management modes.",
  },
  {
    id: "CAR-004",
    title: "Chrysler Pacifica Hybrid",
    category: "Spacious Family Minivan",
    transmission: "Automatic",
    seats: 7,
    fuel_type: "Plug-in Hybrid",
    range_or_mpg: "32 miles EV / 520 total miles",
    price_per_day: 75,
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80",
    description: "The ultimate family road trip vehicle packed with comfort, child safety features, hands-free sliding doors, and rear entertainment screens. Generous Stow 'n Go storage capacity, ultra-soft seats, and smooth hybrid fuel efficiency.",
  },
  {
    id: "CAR-005",
    title: "Mini Cooper SE Convertible",
    category: "Eco City Commuter",
    transmission: "Automatic",
    seats: 4,
    fuel_type: "Electric",
    range_or_mpg: "114 miles range",
    price_per_day: 55,
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=600&q=80",
    description: "A nimble, stylish, and zippy urban electric car custom built for tight city parking, narrow alleyways, and eco-friendly downtown errands. Go-kart handling meets open-top sunshine and zero local emissions.",
  },
  {
    id: "CAR-006",
    title: "Mercedes-Benz S-Class S580",
    category: "Executive Luxury Sedan",
    transmission: "Automatic",
    seats: 5,
    fuel_type: "Gasoline / Mild Hybrid",
    range_or_mpg: "28 MPG",
    price_per_day: 220,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=600&q=80",
    description: "First-class executive luxury on wheels. Whispering-quiet cabin with ambient LED lighting, massaged leather reclining seats, Burmester 4D surround sound system, and supreme air suspension for effortless VIP airport transport or business travel.",
  },
  {
    id: "CAR-007",
    title: "Toyota Rav4 Adventure AWD",
    category: "All-Weather Crossover",
    transmission: "Automatic",
    seats: 5,
    fuel_type: "Gasoline",
    range_or_mpg: "30 MPG",
    price_per_day: 65,
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80",
    description: "A reliable, versatile all-weather compact SUV ready for weekend skiing trips, beach getaways, or muddy countryside drives. Dynamic torque-vectoring AWD, roof rack crossbars for kayaks, and dependable Japanese engineering.",
  },
  {
    id: "CAR-008",
    title: "Chevrolet Corvette Stingray C8",
    category: "Supercar Thrill",
    transmission: "Dual-Clutch Automatic",
    seats: 2,
    fuel_type: "Premium Gasoline",
    range_or_mpg: "24 MPG",
    price_per_day: 290,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=600&q=80",
    description: "Mid-engine exotic performance with striking supercar aesthetics, aggressive aero styling, and 495 horsepower. Perfect for motor enthusiasts looking for exhilarating acceleration, high-speed stability, and heads turning everywhere.",
  },
  {
    id: "CAR-009",
    title: "Volkswagen ID. Buzz Microbus",
    category: "Retro Electric Camper Vibe",
    transmission: "Automatic",
    seats: 7,
    fuel_type: "Electric",
    range_or_mpg: "260 miles range",
    price_per_day: 120,
    image: "https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=600&q=80",
    description: "Reimagined vintage icon with futuristic EV technology. Colorful two-tone interior, modular seating arrangements, surf board roof mounts, and nostalgic feel designed for festival goers, beach lovers, and creative group outings.",
  },
  {
    id: "CAR-010",
    title: "Jeep Wrangler Rubicon Unlimited",
    category: "Trail Master 4x4",
    transmission: "Manual 6-Speed",
    seats: 5,
    fuel_type: "Gasoline",
    range_or_mpg: "20 MPG",
    price_per_day: 105,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
    description: "An authentic, raw manual transmission rock crawler designed for true off-roading aficionados. Tru-Lok front and rear locking differentials, heavy sway bar disconnect, fold-down windshield, and legendary trail capability.",
  },
];
